### PR TITLE
Calendar backend

### PR DESCRIPTION
**Pull request by idavoong**
image
image
image

Issues:
- getWorkouts() is buggy? 
- deleting a workout also deletes a preset

### CODE REVIEW

**Comment by anvch** [comment]
Commenting to review -- As we all discussed in class, since a preset is under a workout, if you delete the first occurrence of the workout it deletes the preset unfortunately -- this is a more major issue we should fix in the future but I think it's fine to leave it as is right now because fixing it would be a big change to how our data is structured. Also, getWorkouts returns workouts without the day(s) it was completed, it only has days created, which is why it's buggy.

**Comment by kjdiaz508** [comment]
Yeah I think it would take too long to change that api. also as a side note, the last pr check always fails. I think it is because it is trying to deploy from this branch, which is not really what we want. It will pass once merged with main though, so it is not a problem

**Comment by Sai-Dhruthik-Murthy** [comment]
Great job. Looks good to me!

**Comment by kjdiaz508** [comment]
looks good. The last test that is not passing is just like that for some reason, not a problem

**Review by kjdiaz508 — APPROVED** [review]

**Pull request merged**
