### PR TITLE
Linking Backend to Home, Profile

### PR DESCRIPTION
**Pull request by anvch**
Updated Home to actually pull username data and populate the My Workouts with preset workouts.
Updated Profile to calculate streak and total workouts this month and display it, as well as populate Recent Workouts with the most recent (up to 5) workouts done/date completed. Also updated name on profile to be the username.

### CODE REVIEW

**Comment by anvch** [comment]
image
image

**Comment by Sai-Dhruthik-Murthy** [comment]
LGTm

**Comment by kjdiaz508** [comment]
To avoid dealing with wierd JS date stuff you convert it to ISO format. It works a lot nicer. To get the current date you would do:
```
date = new Date().toISOString().split("T")[0]
```
and that will give you "2024-11-29" format. We split on T to ignore the time.
To fetch a date using this it would look like this:
```
const [year, month, day] = date
        .split("-")
        .map((val) => parseInt(val, 10));
await WorkoutService.addWorkoutsToCalendar(year, month, day, [workoutId]);
 ```
that splits each individual number and converts it to an int. since JS doesn't care about types very much you may not have to cast to an int, but just to be safe.
You don't have to change anything but just to make your life easier if you decide to do anything else.

**Review by kjdiaz508 — APPROVED** [review]

**Comment by anvch** [comment]
Thank you for the insight, I'll be sure to reference it if I deal with any more dates because it was a pain normalizing them all to be the same date.

**Review by idavoong — APPROVED** [review]

**Comment by idavoong** [comment]
Looks good, great work!

**Pull request merged**
