### PR TITLE
Wourkout entry

### PR DESCRIPTION
**Pull request by kjdiaz508**
Developed the frontend components for inputting new workouts, loading preset workouts, and editing preset workouts.
Projected time for this was about a day.
It took me around two to get it to this point (around 5 hours split up into two days).

Next steps:
- There are some quality of life improvements that would make the front end more intuitive which I want to implement
- The components are not yet linked to the backend. It will take a bit of fiddling to figure that out.

### CODE REVIEW

**Comment by Sai-Dhruthik-Murthy** [comment]
Looks good

**Comment by anvch** [comment]
Looks good to me! Some comments: 
- is there a reason you make classnames {style.___}? It seems to be directly referencing the CSS file. Just asking this for reference if I should do the same for my components to make the code style consistent (since I currently just put a string for the className). 
- I like how it seems that you render the different options (sets/weights vs time/distance) based on whether they did cardio or weights.
- Little confused on the wording for presets -- is it just that whenever you submit a new workout it becomes a new preset and you overwrite existing presets of the same name? Or how do you add presets?

Everything in general looks good to me though, just some more clarification would be helpful.

**Comment by kjdiaz508** [comment]
the {style.classname} and the .module.css files are a feature of the tool that builds our app, and what it does is basically scramble the class names. What that means is that we can style any elements we want inside our .module.css files for that component without it affecting the work that anyone else is doing. Regular css files and class names are global, meaning your css will affect everyone else. I would say switch over if you can, it shouldn't be much work.

The presets are just how Workouts are presented to the user. When I query the data for their workouts I will turn them into presets they can select to be reused.

**Comment by anvch** [comment]
Alright, sounds good. I'll adjust my code to match then.

**Pull request merged**
