### PR TITLE
Added user authentication in backend

### PR DESCRIPTION
**Pull request by Sai-Dhruthik-Murthy**
Used es modules instead of require. modified authModel.js to support user authentication by using the dynamodb table Users. Removed test cases for the backend since we are going to use React component test cases

### CODE REVIEW

**Comment by Sai-Dhruthik-Murthy** [comment]
Summary: Added user authentication in the backend to use the Users table created in Dynamo DB instead of locally storing it.

**Review by kjdiaz508 — APPROVED** [review]
Looks good

**Review by anvch — APPROVED** [review]
Looks good to me, you don't have to delete the testcases though, but up to you.

**Review by idavoong — APPROVED** [review]

**Comment by idavoong** [comment]
Looks good 👍

**Comment by Sai-Dhruthik-Murthy** [comment]
> Looks good to me, you don't have to delete the testcases though, but up to you.

I understand but there were some issues with dependencies for jest tests in the backend and it did not seem worth it to fix and since we decided on react component tests instead I thought its better to just get rid of the backend tests

**Pull request merged**
